//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public bool IsCompleted { get; set; }
        public string Title { get; set; }
        public int EstimatedHours { get; set; }
        public int AppUserId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
